"""Publishes evaluation and benchmark results.

Merges new results into docs/evaluation/phase2_results.json, copies that file to the
dashboard (frontend/public/data/evaluation.json) and renders docs/PHASE2_METRICS.md from it,
so every number in the docs and on the dashboard comes from a recorded run.
"""

from __future__ import annotations

import json
import os
from typing import Any, Dict, Optional

CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(CURRENT_DIR)
RESULTS_PATH = os.path.join(PROJECT_ROOT, "docs", "evaluation", "phase2_results.json")
DASHBOARD_PATH = os.path.join(PROJECT_ROOT, "frontend", "public", "data", "evaluation.json")
SUMMARY_PATH = os.path.join(PROJECT_ROOT, "docs", "PHASE2_METRICS.md")


def pct(value: Optional[float], digits: int = 1) -> str:
    return "n/a" if value is None else f"{100 * value:.{digits}f}%"


def load_results() -> Dict[str, Any]:
    if os.path.exists(RESULTS_PATH):
        with open(RESULTS_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    return {}


def render_markdown(results: Dict[str, Any]) -> str:
    lines = ["# Cygnus AI - Phase 2 metrics", ""]
    lines.append("Generated by `python -m ml.evaluation` and `python -m ml.benchmark`. Do not edit by hand; rerun the scripts.")
    lines.append("")
    model = results.get("model_evaluation")
    if model:
        ds = model["dataset"]
        cmp_ = model["model_comparison"]
        best = cmp_["gbm_graph"]
        rules = cmp_["rules_baseline"]
        phase1 = cmp_["phase1_composite"]
        lines += [
            f"Run at {model['generated_at']} (took {model['runtime_seconds']:.0f} s).",
            "",
            "## Headline numbers",
            "",
            f"- Evaluated on **{ds['test_transactions_total']:,} transactions** across {len(ds['test_networks'])} held-out synthetic MFS networks "
            f"({ds['test_accounts_total']:,} accounts, {ds['test_suspicious_total']:,} labelled suspicious). "
            f"All networks together (train, validation, test): {ds['all_networks_transactions_total']:,} transactions. Phase 1 used 156.",
            f"- Best model (gradient boosting + graph features): **precision {pct(best['precision']['mean'])}, recall {pct(best['recall']['mean'])}, "
            f"F1 {best['f1']['mean']:.3f}, PR-AUC {best['pr_auc']['mean']:.3f}, false-positive rate {pct(best['false_positive_rate']['mean'], 2)}**.",
            f"- Rules-only baseline: precision {pct(rules['precision']['mean'])}, recall {pct(rules['recall']['mean'])}, F1 {rules['f1']['mean']:.3f}, "
            f"PR-AUC {rules['pr_auc']['mean']:.3f}, false-positive rate {pct(rules['false_positive_rate']['mean'], 2)}.",
            f"- Phase 1 Cygnus score on the same data: F1 {phase1['f1']['mean']:.3f}, PR-AUC {phase1['pr_auc']['mean']:.3f}. "
            f"Current product score: F1 {cmp_['cygnus_composite']['f1']['mean']:.3f}, PR-AUC {cmp_['cygnus_composite']['pr_auc']['mean']:.3f}.",
            f"- {ds['n_features']} features per account in 5 families: " + ", ".join(f"{k} {v}" for k, v in ds["features_by_family"].items()) + ".",
            "",
            "## Dataset",
            "",
            ds["description"],
            "",
            "| Network | Transactions | Accounts | Suspicious accounts | Suspicious rate |",
            "|---|---:|---:|---:|---:|",
        ]
        for name, nets, seeds in (("train", ds["train_networks"], ds["train_seeds"]), ("test", ds["test_networks"], ds["test_seeds"])):
            for seed, net in zip(seeds, nets):
                lines.append(f"| {name} (seed {seed}) | {net['transactions']:,} | {net['accounts']:,} | {net['suspicious_accounts']:,} | {pct(net['suspicious_rate'], 2)} |")
        lines += ["", "Typologies planted: " + "; ".join(ds["typologies"].values()) + ".", ""]

        lines += [
            "## Model comparison (mean over held-out networks, +/- standard deviation)",
            "",
            "| Model | Type | Precision | Recall | F1 | PR-AUC | ROC-AUC | False-positive rate | Alerts per 1,000 accounts |",
            "|---|---|---:|---:|---:|---:|---:|---:|---:|",
        ]
        for name, m in cmp_.items():
            lines.append(
                f"| {m['label']} | {m['kind']} | {pct(m['precision']['mean'])} | {pct(m['recall']['mean'])} | "
                f"{m['f1']['mean']:.3f} +/- {m['f1']['std']:.3f} | {m['pr_auc']['mean']:.3f} +/- {m['pr_auc']['std']:.3f} | "
                f"{m['roc_auc']['mean']:.3f} | {pct(m['false_positive_rate']['mean'], 2)} | {m['alerts_per_1000_accounts']['mean']:.1f} |"
            )
        ops = model["operating_points"]
        lines += [
            "",
            "Operating points: rules alert when any rule fires; composite scores alert at 40 and above (MEDIUM+); "
            f"IsolationForest at 3% contamination; supervised models use the threshold with the best F1 on the validation network "
            f"(gradient boosting + graph: {ops['supervised']['gbm_graph']:.3f}).",
            "",
            "## Recall by typology",
            "",
            "| Typology | Accounts | Rules | Graph detectors | IsolationForest | GBM, no graph | GBM + graph |",
            "|---|---:|---:|---:|---:|---:|---:|",
        ]
        for t in model["recall_by_typology"].values():
            r = t["recall"]
            lines.append(f"| {t['label']} | {t['accounts']} | {pct(r['rules_baseline'])} | {pct(r['graph_detectors'])} | {pct(r['isolation_forest'])} | {pct(r['gbm_tabular'])} | {pct(r['gbm_graph'])} |")
        ev = model["recall_evasive_vs_plain"]
        lines += [
            "",
            f"Evasive variants (built to stay under rule thresholds, {ev['evasive_accounts']} accounts): rules catch {pct(ev['evasive']['rules_baseline'])}, "
            f"GBM without graph features {pct(ev['evasive']['gbm_tabular'])}, GBM + graph {pct(ev['evasive']['gbm_graph'])}.",
            "",
            "## What graph intelligence adds over rules",
            "",
        ]
        g = model["graph_vs_rules"]
        lines += [
            f"- Of {g['suspicious_accounts']} suspicious accounts, the rules miss **{g['missed_by_rules']}**. "
            f"The graph model catches **{g['of_those_caught_by_gbm_graph']}** of those; the graph pattern detectors alone catch {g['of_those_caught_by_graph_detectors']}.",
            f"- False positives: rules {g['rule_false_positives']}, graph model {g['gbm_graph_false_positives']}.",
            "",
            "| Typology | Missed by rules | Of those, caught by GBM + graph | Of those, caught by graph detectors |",
            "|---|---:|---:|---:|",
        ]
        for t, row in g["missed_by_rules_by_typology"].items():
            lines.append(f"| {ds['typologies'][t]} | {row['missed_by_rules']} | {row['caught_by_gbm_graph']} | {row['caught_by_graph_detectors']} |")

        lines += ["", "## Feature-family ablation (gradient boosting, PR-AUC on held-out networks)", "", "| Features | Count | PR-AUC |", "|---|---:|---:|"]
        for row in model["feature_ablation"]:
            lines.append(f"| {row['features']} | {row['n_features']} | {row['pr_auc_mean']:.3f} +/- {row['pr_auc_std']:.3f} |")

        fi = model["feature_importance"]
        lines += ["", "## Feature importance", "", fi["method"], "", "| Rank | Feature | Family | PR-AUC drop |", "|---:|---|---|---:|"]
        for i, f in enumerate(fi["top_features"], start=1):
            lines.append(f"| {i} | `{f['feature']}` | {f['family']} | {f['importance']:.4f} |")
        lines += ["", "Share of total importance by family: " + ", ".join(f"{k} {pct(v)}" for k, v in fi["by_family_share"].items()) + ".", ""]

        lines += [
            "## Unseen typology test (leave one typology out of training)",
            "",
            "| Typology held out | Accounts | GBM recall, never trained on it | GBM recall, trained on it | IsolationForest | Graph detectors | Rules |",
            "|---|---:|---:|---:|---:|---:|---:|",
        ]
        for t in model["unseen_typology"].values():
            lines.append(
                f"| {t['label']} | {t['accounts']} | {pct(t['recall_when_never_trained_on_it'])} | {pct(t['recall_when_trained_on_it'])} | "
                f"{pct(t['recall_isolation_forest'])} | {pct(t['recall_graph_detectors'])} | {pct(t['recall_rules'])} |"
            )

        bias = model["bias"]
        lines += [
            "",
            "## Bias check across account tiers",
            "",
            "False-positive rate = share of legitimate accounts of that tier that get an alert.",
            "",
            "| Tier | Legitimate accounts | Rules FPR | Phase 1 score FPR | Current Cygnus score FPR | GBM + graph, no account type | GBM + graph |",
            "|---|---:|---:|---:|---:|---:|---:|",
        ]
        for tier, row in bias["by_account_tier"].items():
            f = row["false_positive_rate"]
            lines.append(f"| {tier} | {row['legitimate_accounts']:,} | {pct(f['rules_baseline'], 2)} | {pct(f['phase1_composite'], 2)} | {pct(f['cygnus_composite'], 2)} | {pct(f['gbm_graph_no_account_type'], 2)} | {pct(f['gbm_graph'], 2)} |")
        gap = bias["false_positive_rate_gap_between_tiers"]
        lines += [
            "",
            "Largest gap in false-positive rate between tiers: " + ", ".join(
                f"{name} {v['gap_percentage_points']:.2f} points" for name, v in gap.items()
            ) + ".",
            "",
        ]
        for name, row in bias["by_district_legitimate_personal_accounts"].items():
            p = row["chi_square_p_value"]
            lines.append(
                f"- By district ({row['districts']} districts, legitimate personal accounts), {name}: false-positive rate between "
                f"{pct(row['min_false_positive_rate'], 2)} and {pct(row['max_false_positive_rate'], 2)}; chi-square p = "
                f"{'n/a' if p is None else f'{p:.3f}'} ({'no evidence of dependence on district' if row['independent_of_district'] else 'depends on district'})."
            )
        lines += ["", bias["note"], ""]

        w = model["workload"]
        lines += [
            "## Analyst workload estimate",
            "",
            f"Assumption: {w['assumption_minutes_per_alert']} minutes of analyst review per alert (an assumption, not a pilot measurement). "
            f"Figures are for the {w['accounts_scored']:,} held-out accounts.",
            "",
            f"- Rules: {w['rules']['alerts']:,} alerts, {w['rules']['true_positives']} true positives (recall {pct(w['rules']['recall'])}), {w['rules']['analyst_hours']:.0f} analyst hours.",
            f"- Graph model: {w['gbm_graph_at_operating_point']['alerts']:,} alerts, {w['gbm_graph_at_operating_point']['true_positives']} true positives "
            f"(recall {pct(w['gbm_graph_at_operating_point']['recall'])}), {w['gbm_graph_at_operating_point']['analyst_hours']:.0f} analyst hours.",
            f"- To find as many suspicious accounts as the rules do, the graph model needs {w['alerts_gbm_needs_to_match_rules_recall']:,} alerts: "
            f"**{pct(w['alert_reduction_at_equal_recall'])} fewer alerts at equal recall**.",
            f"- With the same number of alerts as the rules, the graph model reaches {pct(w['recall_gbm_at_rules_alert_budget'])} recall.",
            f"- Review time per true positive: rules {w['minutes_of_review_per_true_positive']['rules']:.0f} minutes, graph model {w['minutes_of_review_per_true_positive']['gbm_graph']:.0f} minutes.",
            "",
            "## Limitations",
            "",
        ]
        lines += [f"- {item}" for item in model["limitations"]]
        lines.append("")

    bench = results.get("benchmark")
    if bench:
        lines += [
            "## Throughput and latency",
            "",
            f"Run at {bench['generated_at']} on {bench['machine']}.",
            "",
            "### Scoring path (feature store + flow tracing + trained model)",
            "",
            "| Transactions | Accounts | Features (s) | Model scoring (s) | Total (s) | Transactions / second | Peak memory (MB) |",
            "|---:|---:|---:|---:|---:|---:|---:|",
        ]
        for row in bench["scoring_path"]:
            lines.append(
                f"| {row['transactions']:,} | {row['accounts']:,} | {row['feature_seconds']:.2f} | {row['scoring_seconds']:.2f} | "
                f"{row['total_seconds']:.2f} | {row['transactions_per_second']:,.0f} | {row['peak_memory_mb']:.0f} |"
            )
        lines += [
            "",
            "### Full product pipeline (validation + NetworkX graph + 7 detectors + scoring + evidence text)",
            "",
            "| Transactions | Accounts | Total (s) | Transactions / second |",
            "|---:|---:|---:|---:|",
        ]
        for row in bench["full_pipeline"]:
            lines.append(f"| {row['transactions']:,} | {row['accounts']:,} | {row['total_seconds']:.2f} | {row['transactions_per_second']:,.0f} |")
        mb = bench.get("micro_batch")
        if mb:
            lines += [
                "",
                f"Micro-batch re-score of the most recent 24 hours ({mb['transactions']:,} transactions, {mb['accounts']:,} accounts): "
                f"{mb['total_seconds']:.2f} s.",
            ]
        api = bench.get("api_latency")
        if api:
            lines += ["", f"### API latency ({api['requests_per_endpoint']} requests per endpoint, local backend)", "", "| Endpoint | p50 (ms) | p95 (ms) | p99 (ms) |", "|---|---:|---:|---:|"]
            for row in api["endpoints"]:
                lines.append(f"| `{row['endpoint']}` | {row['p50_ms']:.1f} | {row['p95_ms']:.1f} | {row['p99_ms']:.1f} |")
        lines += ["", bench["note"], ""]

    return "\n".join(lines)


def publish(model_results: Optional[Dict[str, Any]] = None, benchmark: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    results = load_results()
    if model_results is not None:
        results["model_evaluation"] = model_results
    if benchmark is not None:
        results["benchmark"] = benchmark
    os.makedirs(os.path.dirname(RESULTS_PATH), exist_ok=True)
    with open(RESULTS_PATH, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)
    os.makedirs(os.path.dirname(DASHBOARD_PATH), exist_ok=True)
    with open(DASHBOARD_PATH, "w", encoding="utf-8") as f:
        json.dump(results, f)
    with open(SUMMARY_PATH, "w", encoding="utf-8") as f:
        f.write(render_markdown(results))
    print(f"wrote {RESULTS_PATH}\nwrote {DASHBOARD_PATH}\nwrote {SUMMARY_PATH}")
    return results


if __name__ == "__main__":
    publish()
